export const authActions = {
	LOGIN_STARTED: "LOGIN_STARTED",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILED: "LOGIN_FAILED",
	SIGNUP_STARTED: "SIGNUP_STARTED",
	SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
	SIGNUP_FAILED: "SIGNUP_FAILED",
};
